name: SparkDataFlow

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Gives the workflow read access to the repository

    steps:
    - uses: actions/checkout@v4
     

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SparkDataFlow
        path: target/*.jar
